// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
import { defineConfig } from "prisma/config";
import secrets from "@repo/secrets"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: secrets.DATABASE_URL,
  },
});
